/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'user' at '12/3/15 9:49 PM' with Gradle 2.3
 *
 * @author user, @date 12/3/15 9:49 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
